[project]
name = "tetrika-junior"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.3",
]

[dependency-groups]
test = [
    "pytest>=8.3.5",
]
dev = [
    "ruff>=0.11.10",
]
